htCommunity_hotTopics:
  class: sfDoctrineRoute
  url: /htCommunity/hotTopics/:id
  options: { model: Community, type: object }
  param: { module: htCommunity, action: hotTopics }
  requirements:
    id: \d+

htDiary_hotDiaries:
  url: /htDiary/hotDiaries
  param: { module: htDiary, action: hotDiaries }

